FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

RUN apt-get update && \
    apt-get install -y python3-dev build-essential curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./pyproject.toml .
COPY wheels/ /tmp/py-wheels
RUN uv sync --find-links /tmp/py-wheels --no-cache

COPY src/ ./

CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
